### ISSUE TITLE
Kicad 6.0 英文版下这是什么问题

### ISSUE THREAD

**Issue by tcjie** [zfeng129/kicad6_jlcpcb_tools#1]
Start generate BOM list
Start generate position file
set board aux origin to left bottom point, at (-100000, 100001) 
Error:
Traceback (most recent call last):
  File "G:\Program Files\KiCad\6.0\share\kicad\scripting\plugins\mf_tool.py", line 790, in Onclick
    GenMFDoc(needGenBOM = self.chkBOM.GetValue(), needGenPos = self.chkPos.GetValue(), logger = lambda *args: self.log(*args) )
  File "G:\Program Files\KiCad\6.0\share\kicad\scripting\plugins\mf_tool.py", line 614, in GenMFDoc
    bomSMDTop = GenBOM(brd, pcbnew.F_Cu, 1, excludeRefs, excludeValues, netList)
  File "G:\Program Files\KiCad\6.0\share\kicad\scripting\plugins\mf_tool.py", line 451, in GenBOM
    bomList[vf] = BOMItem(r,f,v, mod.GetPadCount(), netList)
  File "G:\Program Files\KiCad\6.0\share\kicad\scripting\plugins\mf_tool.py", line 386, in __init__
    if netList.has_key(self.netKey):
AttributeError: 'dict' object has no attribute 'has_key'

**Comment by tcjie** [comment]
dict.has_key() has removed from Python 3.x

**Comment by zfeng129** [comment]
> dict.has_key() has removed from Python 3.x

fix some bug .  you can try again.
